[project]
name = 'procrastination-protocol'
description = '''The only way to win is to do absolutely nothing - Anti-productivity staking game'''
authors = ['man-croft']
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
clarity_version = 2
epoch = '2.5'

[contracts.penalty-pool]
path = 'contracts/penalty-pool.clar'
clarity_version = 2
epoch = '2.5'

[contracts.streak-tracker]
path = 'contracts/streak-tracker.clar'
clarity_version = 2
epoch = '2.5'

[contracts.procrastination-vault]
path = 'contracts/procrastination-vault.clar'
clarity_version = 2
epoch = '2.5'

[contracts.temptation-generator]
path = 'contracts/temptation-generator.clar'
clarity_version = 2
epoch = '2.5'

[contracts.leaderboard]
path = 'contracts/leaderboard.clar'
clarity_version = 2
epoch = '2.5'

[contracts.achievement-nft]
path = 'contracts/achievement-nft.clar'
clarity_version = 2
epoch = '2.5'

[repl.analysis]
passes = [
    'check_checker',
    'call_checker',
]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
